global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets:
          [
            "ISUCON_TRY_SERVER1_IP:9100",
            "ISUCON_TRY_SERVER2_IP:9100",
            "ISUCON_TRY_SERVER3_IP:9100",
          ]

  - job_name: "process_exporter"
    static_configs:
      - targets:
          [
            "ISUCON_TRY_SERVER1_IP:9256",
            "ISUCON_TRY_SERVER2_IP:9256",
            "ISUCON_TRY_SERVER3_IP:9256",
          ]
