global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["54.199.66.128:9100", "18.182.12.217:9100"]

  - job_name: "process_exporter"
    static_configs:
      - targets: ["54.199.66.128:9256", "18.182.12.217:9256"]
