- name: Deploy db_web
  hosts: db_web
  tasks:
    - name: Import mysql_web role
      ansible.builtin.import_role:
        name: mysql_web

- name: Build local
  hosts: localhost
  tasks:
    - name: Build
      ansible.builtin.import_role:
        name: webapp
        tasks_from: build

- name: Configure pdns stuff
  hosts: webapp
  tasks:
    - name: Deploy
      ansible.builtin.import_role:
        name: webapp
        tasks_from: configure

- name: Deploy remote
  hosts: webapp
  become_user: isucon
  tasks:
    - name: Deploy
      ansible.builtin.import_role:
        name: webapp
        tasks_from: deploy
