all:
  vars:
    hosts_ips:
      S1: 54.249.3.81
      S2: 35.72.5.243

  children:
    target:
      children:
        nginx:
          hosts:
            nginx01:
              ansible_host: "{{ hosts_ips.S1 }}"
        webapp:
          hosts:
            webapp01:
              ansible_host: "{{ hosts_ips.S1 }}"
        db_web:
          hosts:
            db01:
              ansible_host: "{{ hosts_ips.S1 }}"
        pdns:
          hosts:
            pdns01:
              ansible_host: "{{ hosts_ips.S1 }}"
        db_pdns:
          hosts:
            db01:
              ansible_host: "{{ hosts_ips.S2 }}"
    outsider:
      hosts:
        benchmarker:
          ansible_host: "{{ hosts_ips.S2 }}"
