all:
  children:
    target:
      nginx:
        hosts:
          nginx01:
            ansible_host: 52.68.30.27
      webapp:
        hosts:
          webapp01:
            ansible_host: 52.68.30.27
      db:
        hosts:
          db01:
            ansible_host: 52.68.30.27
      pdns:
        hosts:
          pdns01:
            ansible_host: 52.68.30.27
    outsider:
      hosts:
        benchmarker:
          ansible_host: 13.230.223.90
