all:
  vars:
    hosts_ips:
      S1: 54.199.66.128
      S2: 18.182.12.217

  children:
    target:
      children:
        nginx:
          hosts:
            nginx01:
              ansible_host: "{{ hosts_ips.S1 }}"
        webapp:
          hosts:
            webapp01:
              ansible_host: "{{ hosts_ips.S1 }}"
        db_web:
          hosts:
            db_web01:
              ansible_host: "{{ hosts_ips.S1 }}"
        pdns:
          hosts:
            pdns01:
              ansible_host: "{{ hosts_ips.S1 }}"
        db_pdns:
          hosts:
            db_pdns01:
              ansible_host: "{{ hosts_ips.S2 }}"
    outsider:
      hosts:
        benchmarker:
          ansible_host: "{{ hosts_ips.S2 }}"
