all:
  children:
    nginx:
      hosts:
        nginx01:
          ansible_host: 43.206.223.217
    webapp:
      hosts:
        webapp01:
          ansible_host: 43.206.223.217
    db:
      hosts:
        db01:
          ansible_host: 43.206.223.217
    pdns:
      hosts:
        pdns01:
          ansible_host: 43.206.223.217
